# Generated by Django 5.0.6 on 2024-07-14 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('grade', models.CharField(choices=[('6-7', '6-7'), ('6-8', '6-8'), ('7-9', '7-9'), ('srednja škola', 'Srednja Škola')], default='6-7', max_length=99)),
                ('term', models.CharField(choices=[('zimski', 'Zimski'), ('ljetnji', 'Ljetnji')], default='zimski', max_length=99)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, default='seid.webp', null=True, upload_to='course_images/')),
                ('length', models.CharField(default='12 nedelja', max_length=99)),
                ('weekly_hours', models.CharField(default='3 sata nedeljno', max_length=99)),
                ('is_active', models.BooleanField(default=True)),
                ('level', models.CharField(choices=[('osnovni', 'Osnovni'), ('Srednji', 'Srednji'), ('Napredni', 'Napredni')], default='osnovni', max_length=20)),
                ('course_type', models.CharField(choices=[('matematika', 'Matematika'), ('fizika', 'Fizika')], default='matematika', max_length=20)),
                ('school_type', models.CharField(choices=[('osnovna škola', 'Osnovna škola'), ('srednja škola', 'Srednja škola')], default='osnovna škola', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='user_app.profile')),
            ],
        ),
    ]
