# Generated by Django 5.0.6 on 2024-07-28 12:42

import djrichtextfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.CharField(choices=[('I polugođe', 'I polugođe'), ('II polugođe', 'II polugođe')], default='I polugođe', max_length=99),
        ),
        migrations.AlterField(
            model_name='course',
            name='weekly_hours',
            field=models.CharField(default='2x90 min nedeljno', max_length=99),
        ),
    ]
